**This notebook will be used only for the capstone project**

In [95]:
import pandas as pd
import numpy as np

In [96]:
table = pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
print (table[0])

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
282      M8Z         Etobicoke              Mimico NW
283      M8Z         Etobicoke     The Queensway West
284      M8Z         Etobicoke  Royal York South West
285      M8Z         Etobicoke         South of Bloor
286      M9Z      Not assigned           Not assigned

[287 rows x 3 columns]

In [97]:
data = pd.DataFrame(table[0])
data.head(10)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor
7      M7A  Downtown Toronto      Queen's Park
8      M8A      Not assigned      Not assigned
9      M9A      Queen's Park      Not assigned

In [98]:
df = data.groupby(['Postcode', 'Borough'])['Neighbourhood'].apply(list)
df = df.sample(frac=1).reset_index()
df['Neighbourhood'] = df['Neighbourhood'].str.join(', ')
df

,Postcode,Borough,Neighbourhood
0,M4V,Central Toronto,"Deer Park, Forest Hill SE, Rathnelly, South Hi..."
1,M4Y,Downtown Toronto,Church and Wellesley
2,M4M,East Toronto,Studio District
3,M6G,Downtown Toronto,Christie
4,M2V,Not assigned,Not assigned
...,...,...,...
175,M5R,Central Toronto,"The Annex, North Midtown, Yorkville"
176,M3B,North York,Don Mills North
177,M9G,Not assigned,Not assigned
178,M2S,Not assigned,Not assigned
179,M4A,North York,Victoria Village

In [104]:
df=df[df['Borough']!='Not assigned']
df[df['Neighbourhood']=='Not assigned']=df['Borough']
df

,Postcode,Borough,Neighbourhood
0,M4V,Central Toronto,"Deer Park, Forest Hill SE, Rathnelly, South Hi..."
1,M4Y,Downtown Toronto,Church and Wellesley
2,M4M,East Toronto,Studio District
3,M6G,Downtown Toronto,Christie
5,M9M,North York,"Emery, Humberlea"
...,...,...,...
170,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
171,M1B,Scarborough,"Rouge, Malvern"
175,M5R,Central Toronto,"The Annex, North Midtown, Yorkville"
176,M3B,North York,Don Mills North
179,M4A,North York,Victoria Village

In [105]:
df.shape

(103, 3)